name: CI

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: npm-shrinkwrap.json
      - name: Install
        run: npm ci
      - name: Check syntax
        run: |
          node --check app.js
          node --check common.js
